version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Check yarn version
      - yarn -v
      - echo yarn install
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
      - cp appspec.yml dist
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  exclude-paths:
    - "favicon.ico"
